apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cassandra: cassandra1
    contrail_manager: cassandra
  name: cassandra1-pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  local:
    path: /mnt/cassandra
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: In
          values:
          - ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  volumeMode: Filesystem
